/**
 * @license
 * Copyright 2018 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =============================================================================
 */

export const SCAVENGER_CLASSES: {[key: number]: string} = {
     0: 'kimono',
     1: 'truck',
     2: 'plunger',
     3: 'desk',
     4: 'school bus',
     5: 'toaster',
     6: 'shovel',
     7: 'football helmet',
     8: 'building',
     9: 'fire engine',
    10: 'cowboy boot',
    11: 'sleeping bag',
    12: 'airship',
    13: 'spoon',
    14: 'plane',
    15: 'sliding door',
    16: 'china cabinet',
    17: 'vault',
    18: 'bullet train',
    19: 'microwave',
    20: 'theater curtain',
    21: 'barn',
    22: 'oscilloscope',
    23: 'pedestal',
    24: 'lampshade',
    25: 'gondola',
    26: 'valley',
    27: 'zucchini',
    28: 'knot',
    29: 'hot pot',
    30: 'clock',
    31: 'envelope',
    32: 'tray',
    33: 'bassinet',
    34: 'cannon',
    35: 'menu',
    36: 'mouse',
    37: 'stove',
    38: 'barbell',
    39: 'bath towel',
    40: 'handkerchief',
    41: 'pool table',
    42: 'motor scooter',
    43: 'goblet',
    44: 'stone wall',
    45: 'microphone',
    46: 'washer',
    47: 'hand',
    48: 'gown',
    49: 'tennis ball',
    50: 'wig',
    51: 'bathtub',
    52: 'totem pole',
    53: 'shower curtain',
    54: 'broom',
    55: 'measuring cup',
    56: 'mountain tent',
    57: 'table lamp',
    58: 'barrow',
    59: 'golf ball',
    60: 'broccoli',
    61: 'bed',
    62: 'electric fan',
    63: 'flute',
    64: 'tobacco shop',
    65: 'crock pot',
    66: 'harmonica',
    67: 'shoe shop',
    68: 'water jug',
    69: 'ping pong ball',
    70: 'lipstick',
    71: 'dining table',
    72: 'banjo',
    73: 'confectionery',
    74: 'watch',
    75: 'crossword puzzle',
    76: 'modem',
    77: 'saltshaker',
    78: 'tile roof',
    79: 'refrigerator',
    80: 'mailbox',
    81: 'pole',
    82: 'cello',
    83: 'flagpole',
    84: 'water tower',
    85: 'barber chair',
    86: 'yawl',
    87: 'soap dispenser',
    88: 'stretcher',
    89: 'steel drum',
    90: 'bottlecap',
    91: 'bathing cap',
    92: 'comic book',
    93: 'go kart',
    94: 'dam',
    95: 'parallel bars',
    96: 'hand blower',
    97: 'scoreboard',
    98: 'space shuttle',
    99: 'lakeside',
   100: 'ocarina',
   101: 'crutch',
   102: 'cardigan',
   103: 'milk can',
   104: 'pencil box',
   105: 'home theater',
   106: 'feather boa',
   107: 'solar dish',
   108: 'dial telephone',
   109: 'lighter',
   110: 'light bulb',
   111: 'sewing machine',
   112: 'tv',
   113: 'toilet tissue',
   114: 'combination lock',
   115: 'cloak',
   116: 'bowl',
   117: 'croquet ball',
   118: 'container ship',
   119: 'dogsled',
   120: 'lock',
   121: 'potters wheel',
   122: 'plug',
   123: 'horizontal bar',
   124: 'castle',
   125: 'rocking chair',
   126: 'balloon',
   127: 'ramen',
   128: 'crayfish',
   129: 'mixing bowl',
   130: 'oboe',
   131: 'nail',
   132: 'hamburger',
   133: 'patio',
   134: 'spindle',
   135: 'cucumber',
   136: 'window shade',
   137: 'street sign',
   138: 'carousel',
   139: 'rain barrel',
   140: 'barrel',
   141: 'carton',
   142: 'baby bottle',
   143: 'screw',
   144: 'lion',
   145: 'crate',
   146: 'volleyball',
   147: 'flower',
   148: 'shirt',
   149: 'koala',
   150: 'necklace',
   151: 'book',
   152: 'sunglasses',
   153: 'hair spray',
   154: 'bicycle',
   155: 'buckle',
   156: 'shopping basket',
   157: 'dog',
   158: 'cellphone',
   159: 'rubber eraser',
   160: 'golfcart',
   161: 'christmas stocking',
   162: 'hourglass',
   163: 'hammer',
   164: 'pop bottle',
   165: 'candle',
   166: 'spotlight',
   167: 'pickup',
   168: 'pill bottle',
   169: 'can opener',
   170: 'freight car',
   171: 'wardrobe',
   172: 'maraca',
   173: 'matchstick',
   174: 'ant',
   175: 'park bench',
   176: 'teapot',
   177: 'camera',
   178: 'reel',
   179: 'space heater',
   180: 'bow',
   181: 'racket',
   182: 'perfume',
   183: 'scale',
   184: 'hotdog',
   185: 'basketball',
   186: 'sea urchin',
   187: 'umbrella',
   188: 'coral reef',
   189: 'tripod',
   190: 'strawberry',
   191: 'sushi',
   192: 'chime',
   193: 'bus',
   194: 'snowplow',
   195: 'icecream',
   196: 'soccer ball',
   197: 'canoe',
   198: 'velvet',
   199: 'police van',
   200: 'vending machine',
   201: 'fireboat',
   202: 'mailbag',
   203: 'electric locomotive',
   204: 'seashore',
   205: 'glove',
   206: 'cup',
   207: 'plate rack',
   208: 'car wheel',
   209: 'cuirass',
   210: 'projector',
   211: 'mashed potato',
   212: 'espresso maker',
   213: 'pizza',
   214: 'tricycle',
   215: 'steam locomotive',
   216: 'miniskirt',
   217: 'hoopskirt',
   218: 'baseball',
   219: 'volcano',
   220: 'dishwasher',
   221: 'piggy bank',
   222: 'orange',
   223: 'garbage truck',
   224: 'espresso',
   225: 'corn',
   226: 'iron',
   227: 'honeycomb',
   228: 'trombone',
   229: 'apron',
   230: 'ski mask',
   231: 'tree',
   232: 'joystick',
   233: 'flashlight',
   234: 'punching bag',
   235: 'mask',
   236: 'ladybug',
   237: 'burrito',
   238: 'chain',
   239: 'dumbbell',
   240: 'lotion',
   241: 'wallet',
   242: 'lens cap',
   243: 'medicine chest',
   244: 'planetarium',
   245: 'artichoke',
   246: 'snowmobile',
   247: 'guacamole',
   248: 'odometer',
   249: 'screwdriver',
   250: 'mortarboard',
   251: 'cassette player',
   252: 'paintbrush',
   253: 'birdhouse',
   254: 'car',
   255: 'radio',
   256: 'hat',
   257: 'safety pin',
   258: 'fountain',
   259: 'tiger',
   260: 'pinwheel',
   261: 'restaurant',
   262: 'bib',
   263: 'display',
   264: 'cabinet',
   265: 'sundial',
   266: 'tow truck',
   267: 'stage',
   268: 'whistle',
   269: 'mobile home',
   270: 'scorpion',
   271: 'fish',
   272: 'barometer',
   273: 'bucket',
   274: 'jigsaw puzzle',
   275: 'key',
   276: 'pick',
   277: 'band aid',
   278: 'power drill',
   279: 'speedboat',
   280: 'scissors',
   281: 'lemon',
   282: 'mushroom',
   283: 'french horn',
   284: 'bubble',
   285: 'pineapple',
   286: 'wool',
   287: 'shopping cart',
   288: 'gong',
   289: 'tractor',
   290: 'pajama',
   291: 'scarf',
   292: 'cd player',
   293: 'marimba',
   294: 'crib',
   295: 'airliner',
   296: 'cat',
   297: 'ski',
   298: 'laptop',
   299: 'jack o lantern',
   300: 'bread',
   301: 'frying pan',
   302: 'abacus',
   303: 'butcher shop',
   304: 'fries',
   305: 'streetcar',
   306: 'parking meter',
   307: 'shower cap',
   308: 'paper towel',
   309: 'oil filter',
   310: 'pot',
   311: 'beer',
   312: 'greenhouse',
   313: 'strainer',
   314: 'bee',
   315: 'vase',
   316: 'forklift',
   317: 'guitar',
   318: 'pomegranate',
   319: 'backpack',
   320: 'donut',
   321: 'crane',
   322: 'prayer rug',
   323: 'dungeness crab',
   324: 'corkscrew',
   325: 'snorkel',
   326: 'cauliflower',
   327: 'sarong',
   328: 'pencil sharpener',
   329: 'sax',
   330: 'ladle',
   331: 'pants',
   332: 'slot',
   333: 'house',
   334: 'parachute',
   335: 'doormat',
   336: 'window screen',
   337: 'bird',
   338: 'balance beam',
   339: 'coil',
   340: 'giant panda',
   341: 'pillow',
   342: 'disk brake',
   343: 'pirate',
   344: 'aircraft carrier',
   345: 'knee pad',
   346: 'car mirror',
   347: 'trash can',
   348: 'hair slide',
   349: 'pen',
   350: 'door',
   351: 'safe',
   352: 'cassette',
   353: 'swing',
   354: 'plate',
   355: 'banana',
   356: 'crash helmet',
   357: 'drum',
   358: 'face powder',
   359: 'diaper',
   360: 'poncho',
   361: 'quilt',
   362: 'pitcher',
   363: 'toyshop',
   364: 'coat',
   365: 'binoculars',
   366: 'acorn',
   367: 'swimming trunks',
   368: 'rotisserie',
   369: 'abaya',
   370: 'ballplayer',
   371: 'folding chair',
   372: 'water bottle',
   373: 'taco',
   374: 'starfish',
   375: 'spider web',
   376: 'cash machine',
   377: 'hard disc',
   378: 'manhole cover',
   379: 'hamper',
   380: 'letter opener',
   381: 'oxygen mask',
   382: 'cradle',
   383: 'newspaper',
   384: 'groom',
   385: 'radiator',
   386: 'plastic bag',
   387: 'traffic light',
   388: 'bell pepper',
   389: 'cliff',
   390: 'piano',
   391: 'gas pump',
   392: 'sock',
   393: 'swab',
   394: 'magnetic compass',
   395: 'headphones',
   396: 'worm fence',
   397: 'organ',
   398: 'cocktail shaker',
   399: 'snail',
   400: 'slug',
   401: 'hook',
   402: 'shoe',
   403: 'mosque',
   404: 'toilet',
   405: 'vacuum',
   406: 'harp',
   407: 'scuba diver',
   408: 'wine',
   409: 'puck',
   410: 'chiffonier',
   411: 'accordion',
   412: 'remote control',
   413: 'printer',
   414: 'violin',
   415: 'magnifying glass',
   416: 'sofa',
   417: 'sunscreen',
   418: 'sandbar',
   419: 'steel arch bridge',
   420: 'spatula',
   421: 'keyboard',
   422: 'switch',
   423: 'rugby ball',
};

export const CLASS_LABELS_JA: {[key: string]: string} = {
    'kimono': '着物',
    'truck': 'トラック',
    'plunger': 'スッポン',
    'desk': '机',
    'school bus': 'スクールバス',
    'toaster': 'トースター',
    'shovel': 'シャベル',
    'football helmet': 'アメフトのヘルメット',
    'building': 'ビル',
    'fire engine': '消防車',
    'cowboy boot': 'カウボーイブーツ',
    'sleeping bag': '寝袋',
    'airship': '飛行船',
    'spoon': 'スプーン',
    'plane': '飛行機',
    'sliding door': '引き戸',
    'china cabinet': 'タンス',
    'vault': 'アーチ型の天井',
    'bullet train': '新幹線',
    'microwave': '電子レンジ',
    'theater curtain': '劇場の幕',
    'barn': '小屋',
    'oscilloscope': 'オシロスコープ',
    'pedestal': '台座',
    'lampshade': 'ランプのかさ',
    'gondola': 'ゴンドラ',
    'valley': '谷',
    'zucchini': 'ズッキーニ',
    'knot': '結び目',
    'hot pot': '鍋',
    'clock': '時計',
    'envelope': '封筒',
    'tray': 'トレイ',
    'bassinet': 'バシネット',
    'cannon': '大砲',
    'menu': 'メニュー',
    'mouse': 'マウス',
    'stove': 'ストーブ',
    'barbell': 'バーベル',
    'bath towel': 'バスタオル',
    'handkerchief': 'ハンカチ',
    'pool table': 'ビリヤード台',
    'motor scooter': 'スクーター',
    'goblet': 'ゴブレット',
    'stone wall': '石垣',
    'microphone': 'マイク',
    'washer': '洗濯機',
    'hand': '手',
    'gown': 'ガウン',
    'tennis ball': 'テニスボール',
    'wig': 'かつら',
    'bathtub': 'バスタブ',
    'totem pole': 'トーテムポール',
    'shower curtain': 'シャワーカーテン',
    'broom': 'ほうき',
    'measuring cup': '計量カップ',
    'mountain tent': '山のテント',
    'table lamp': '電気スタンド',
    'barrow': '手押し車',
    'golf ball': 'ゴルフボール',
    'broccoli': 'ブロッコリー',
    'bed': 'ベッド',
    'electric fan': '扇風機',
    'flute': 'フルート',
    'tobacco shop': 'タバコ店',
    'crock pot': 'スロークッカー',
    'harmonica': 'ハーモニカ',
    'shoe shop': '靴屋',
    'water jug': '水差し',
    'ping pong ball': 'ピンポン球',
    'lipstick': '口紅',
    'dining table': 'ダイニングテーブル',
    'banjo': 'バンジョー',
    'confectionery': '製菓',
    'watch': '腕時計',
    'crossword puzzle': 'クロスワードパズル',
    'modem': 'モデム',
    'saltshaker': 'ソルトシェーカー',
    'tile roof': '瓦屋根',
    'refrigerator': '冷蔵庫',
    'mailbox': '郵便受け',
    'pole': 'ポール',
    'cello': 'チェロ',
    'flagpole': '旗ざお',
    'water tower': '給水塔',
    'barber chair': '床屋の椅子',
    'yawl': 'ヨット',
    'soap dispenser': 'ソープディスペンサー',
    'stretcher': '担架',
    'steel drum': 'スチールドラム',
    'bottlecap': '瓶のキャップ',
    'bathing cap': 'ヘアキャップ',
    'comic book': '漫画本',
    'go kart': 'ゴーカート',
    'dam': 'ダム',
    'parallel bars': '平行棒',
    'hand blower': 'ハンドブロワー',
    'scoreboard': 'スコアボード',
    'space shuttle': 'スペースシャトル',
    'lakeside': '湖畔',
    'ocarina': 'オカリナ',
    'crutch': '松葉杖',
    'cardigan': 'カーディガン',
    'milk can': 'ミルク缶',
    'pencil box': '筆箱',
    'home theater': 'ホームシアター',
    'feather boa': 'ボア',
    'solar dish': '凹面鏡',
    'dial telephone': 'ダイヤル電話',
    'lighter': 'ライター',
    'light bulb': '電球',
    'sewing machine': 'ミシン',
    'tv': 'テレビ',
    'toilet tissue': 'トイレットペーパー',
    'combination lock': 'ダイアル錠',
    'cloak': 'クローク',
    'bowl': 'ボウル',
    'croquet ball': 'クロケットのボール',
    'container ship': 'コンテナ船',
    'dogsled': '犬ぞり',
    'lock': 'ロック',
    'potters wheel': 'ろくろ',
    'plug': 'プラグ',
    'horizontal bar': '鉄棒',
    'castle': '城',
    'rocking chair': 'ロッキングチェア',
    'balloon': '風船',
    'ramen': 'ラーメン',
    'crayfish': 'ザリガニ',
    'mixing bowl': 'ミキシングボウル',
    'oboe': 'オーボエ',
    'nail': 'ネイル',
    'hamburger': 'ハンバーガー',
    'patio': 'パティオ',
    'spindle': 'スピンドル',
    'cucumber': 'きゅうり',
    'window shade': 'ブラインド',
    'street sign': '道路標識',
    'carousel': 'メリーゴーランド',
    'rain barrel': '雨桶',
    'barrel': '樽',
    'carton': '漫画',
    'baby bottle': '哺乳瓶',
    'screw': 'ネジ',
    'lion': 'ライオン',
    'crate': '木箱',
    'volleyball': 'バレーボール',
    'flower': '花',
    'shirt': 'シャツ',
    'koala': 'コアラ',
    'necklace': 'ネックレス',
    'book': '本',
    'sunglasses': 'サングラス',
    'hair spray': 'ヘアスプレー',
    'bicycle': '自転車',
    'buckle': 'バックル',
    'shopping basket': '買い物かご',
    'dog': '犬',
    'cellphone': '携帯電話',
    'rubber eraser': '消しゴム',
    'golfcart': 'ゴルフカート',
    'christmas stocking': 'クリスマスの靴下',
    'hourglass': '砂時計',
    'hammer': 'ハンマー',
    'pop bottle': 'ボトル',
    'candle': 'ろうそく',
    'spotlight': 'スポットライト',
    'pickup': 'トラック',
    'pill bottle': '錠剤瓶',
    'can opener': '缶切り',
    'freight car': '貨車',
    'wardrobe': '衣装ダンス',
    'maraca': 'マラカス',
    'matchstick': 'マッチ棒',
    'ant': 'アリ',
    'park bench': '公園のベンチ',
    'teapot': 'ティーポット',
    'camera': 'カメラ',
    'reel': 'リール',
    'space heater': '小型ヒーター',
    'bow': '弓',
    'racket': 'ラケット',
    'perfume': '香水',
    'scale': 'はかり',
    'hotdog': 'ホットドッグ',
    'basketball': 'バスケットボール',
    'sea urchin': 'うに',
    'umbrella': '傘',
    'coral reef': '珊瑚礁',
    'tripod': '三脚',
    'strawberry': 'イチゴ',
    'sushi': '寿司',
    'chime': 'チャイム',
    'bus': 'バス',
    'snowplow': '除雪機',
    'icecream': 'アイスクリーム',
    'soccer ball': 'サッカーボール',
    'canoe': 'カヌー',
    'velvet': 'ベルベット',
    'police van': '警察車両',
    'vending machine': '自動販売機',
    'fireboat': '消防艇',
    'mailbag': '郵袋',
    'electric locomotive': '電気機関車',
    'seashore': '海辺',
    'glove': '手袋',
    'cup': 'カップ',
    'plate rack': '水切りカゴ',
    'car wheel': '車のホイール',
    'cuirass': 'よろい',
    'projector': 'プロジェクター',
    'mashed potato': 'マッシュポテト',
    'espresso maker': 'エスプレッソメーカー',
    'pizza': 'ピザ',
    'tricycle': '三輪車',
    'steam locomotive': '蒸気機関車',
    'miniskirt': 'ミニスカート',
    'hoopskirt': 'フープスカート',
    'baseball': '野球ボール',
    'volcano': '火山',
    'dishwasher': '食器洗い機',
    'piggy bank': '貯金箱',
    'orange': 'オレンジ',
    'garbage truck': 'ごみ収集車',
    'espresso': 'エスプレッソ',
    'corn': 'コーン',
    'iron': 'アイロン',
    'honeycomb': '蜂の巣',
    'trombone': 'トロンボーン',
    'apron': 'エプロン',
    'ski mask': '目出し帽',
    'tree': '木',
    'joystick': 'ジョイスティック',
    'flashlight': '懐中電灯',
    'punching bag': 'サンドバッグ',
    'mask': 'マスク',
    'ladybug': 'てんとう虫',
    'burrito': 'ブリトー',
    'chain': '鎖',
    'dumbbell': 'ダンベル',
    'lotion': 'ローション',
    'wallet': '財布',
    'lens cap': 'レンズキャップ',
    'medicine chest': '薬箱',
    'planetarium': 'プラネタリウム',
    'artichoke': 'アーティチョーク',
    'snowmobile': 'スノーモービル',
    'guacamole': 'グアカモーレ',
    'odometer': '走行距離計',
    'screwdriver': 'ドライバー',
    'mortarboard': 'モルタルボード',
    'cassette player': 'カセット・プレーヤー',
    'paintbrush': '筆',
    'birdhouse': '巣箱',
    'car': '車',
    'radio': 'ラジオ',
    'hat': '帽子',
    'safety pin': '安全ピン',
    'fountain': '噴水',
    'tiger': 'トラ',
    'pinwheel': '風車',
    'restaurant': 'レストラン',
    'bib': 'よだれかけ',
    'display': 'ディスプレイ',
    'cabinet': 'キャビネット',
    'sundial': '日時計',
    'tow truck': 'レッカー車',
    'stage': 'ステージ',
    'whistle': 'ホイッスル',
    'mobile home': '移動住宅',
    'scorpion': '蠍',
    'fish': '魚',
    'barometer': 'バロメーター',
    'bucket': 'バケツ',
    'jigsaw puzzle': 'ジグソーパズル',
    'key': 'キー',
    'pick': 'ピック',
    'band aid': 'バンドエイド',
    'power drill': '電動ドリル',
    'speedboat': 'スピードボート',
    'scissors': 'はさみ',
    'lemon': 'レモン',
    'mushroom': 'キノコ',
    'french horn': 'フレンチホルン',
    'bubble': '泡',
    'pineapple': 'パイナップル',
    'wool': 'ウール',
    'shopping cart': 'ショッピングカート',
    'gong': 'ゴング',
    'tractor': 'トラクター',
    'pajama': 'パジャマ',
    'scarf': 'スカーフ',
    'cd player': 'CDプレーヤー',
    'marimba': 'マリンバ',
    'crib': 'ベビーベッド',
    'airliner': '旅客機',
    'cat': 'ネコ',
    'ski': 'スキー',
    'laptop': 'ノートパソコン',
    'jack o lantern': 'ジャックランタン',
    'bread': 'パン',
    'frying pan': 'フライパン',
    'abacus': 'ソロバン',
    'butcher shop': '精肉店',
    'fries': 'フライドポテト',
    'streetcar': 'ストリートカー',
    'parking meter': 'パーキングメーター',
    'shower cap': 'シャワーキャップ',
    'paper towel': 'ペーパータオル',
    'oil filter': 'オイルフィルター',
    'pot': 'ポット',
    'beer': 'ビール',
    'greenhouse': '温室',
    'strainer': '漉し器',
    'bee': '蜂',
    'vase': '花瓶',
    'forklift': 'フォークリフト',
    'guitar': 'ギター',
    'pomegranate': 'ザクロ',
    'backpack': 'バックパック',
    'donut': 'ドーナツ',
    'crane': 'クレーン',
    'prayer rug': '祈りの敷物',
    'dungeness crab': 'カニ',
    'corkscrew': 'コルク抜き',
    'snorkel': 'スノーケル',
    'cauliflower': 'カリフラワー',
    'sarong': 'サロン',
    'pencil sharpener': '鉛筆削り',
    'sax': 'サックス',
    'ladle': 'おたま',
    'pants': 'パンツ',
    'slot': 'スロット',
    'house': '家',
    'parachute': 'パラシュート',
    'doormat': 'ドアマット',
    'window screen': '網戸',
    'bird': '鳥',
    'balance beam': '平均台',
    'coil': 'コイル',
    'giant panda': 'ジャイアントパンダ',
    'pillow': '枕',
    'disk brake': 'ディスクブレーキ',
    'pirate': '海賊',
    'aircraft carrier': '空母',
    'knee pad': '膝パッド',
    'car mirror': '車のミラー',
    'trash can': 'ごみ箱',
    'hair slide': 'かんざし',
    'pen': 'ペン',
    'door': 'ドア',
    'safe': '金庫',
    'cassette': 'カセット',
    'swing': 'ブランコ',
    'plate': 'お皿',
    'banana': 'バナナ',
    'crash helmet': 'ヘルメット',
    'drum': 'ドラム',
    'face powder': 'ファンデーション',
    'diaper': 'おむつ',
    'poncho': 'ポンチョ',
    'quilt': 'キルト',
    'pitcher': 'ピッチャー',
    'toyshop': '玩具屋',
    'coat': 'コート',
    'binoculars': '双眼鏡',
    'acorn': 'どんぐり',
    'swimming trunks': '海パン',
    'rotisserie': '丸焼きチキン',
    'abaya': 'アバヤ',
    'ballplayer': '野球選手',
    'folding chair': '折り畳みいす',
    'water bottle': '水筒',
    'taco': 'タコス',
    'starfish': 'ヒトデ',
    'spider web': '蜘蛛の巣',
    'cash machine': 'ATM',
    'hard disc': 'ハードディスク',
    'manhole cover': 'マンホールの蓋',
    'hamper': 'かご',
    'letter opener': 'レターオープナー',
    'oxygen mask': '酸素マスク',
    'cradle': 'ゆりかご',
    'newspaper': '新聞',
    'groom': '新郎',
    'radiator': 'ラジエーター',
    'plastic bag': 'ビニール袋',
    'traffic light': '信号機',
    'bell pepper': 'ピーマン',
    'cliff': '崖',
    'piano': 'ピアノ',
    'gas pump': 'ガスポンプ',
    'sock': '靴下',
    'swab': 'モップ',
    'magnetic compass': '方位磁針',
    'headphones': 'ヘッドフォン',
    'worm fence': 'ジグザグ形のへい.',
    'organ': 'オルガン',
    'cocktail shaker': 'カクテルシェーカー',
    'snail': 'かたつむり',
    'slug': 'ナメクジ',
    'hook': 'フック',
    'shoe': '靴',
    'mosque': 'モスク',
    'toilet': 'トイレ',
    'vacuum': '掃除機',
    'harp': 'ハープ',
    'scuba diver': 'スキューバダイバー',
    'wine': 'ワイン',
    'puck': 'アイスホッケーのパック',
    'chiffonier': '洋だんす',
    'accordion': 'アコーディオン',
    'remote control': 'リモコン',
    'printer': 'プリンタ',
    'violin': 'バイオリン',
    'magnifying glass': '虫眼鏡',
    'sofa': 'ソファー',
    'sunscreen': '日焼け止め',
    'sandbar': 'サンドバー',
    'steel arch bridge': '鉄橋',
    'spatula': 'スパチュラ',
    'keyboard': 'キーボード',
    'switch': 'スイッチ',
    'rugby ball': 'ラグビーボール',
};
